-- Structura pentru Limba română: clase -> capitole -> materiale PDF
create table if not exists public.limba_clase (
    id bigint generated by default as identity primary key,
    numar smallint not null unique check (numar between 5 and 8),
    titlu text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.limba_capitole (
    id bigint generated by default as identity primary key,
    clasa_id bigint not null references public.limba_clase(id) on delete cascade,
    titlu text not null,
    descriere text,
    ordine integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.limba_materiale (
    id bigint generated by default as identity primary key,
    capitol_id bigint not null references public.limba_capitole(id) on delete cascade,
    titlu text not null,
    descriere text,
    pdf text not null,
    ordine integer not null default 0,
    created_at timestamptz not null default now()
);

insert into public.limba_clase (numar, titlu)
values
    (5, 'Clasa a V-a'),
    (6, 'Clasa a VI-a'),
    (7, 'Clasa a VII-a'),
    (8, 'Clasa a VIII-a')
on conflict (numar) do update set titlu = excluded.titlu;

create index if not exists limba_capitole_clasa_id_idx
    on public.limba_capitole (clasa_id, ordine);

create index if not exists limba_materiale_capitol_id_idx
    on public.limba_materiale (capitol_id, ordine);

alter table public.limba_clase enable row level security;
alter table public.limba_capitole enable row level security;
alter table public.limba_materiale enable row level security;

create policy "Limba română este vizibilă public"
    on public.limba_clase for select using (true);
create policy "Capitolele de limbă sunt vizibile public"
    on public.limba_capitole for select using (true);
create policy "Materialele de limbă sunt vizibile public"
    on public.limba_materiale for select using (true);

create policy "Doar administratorii gestionează clasele"
    on public.limba_clase for all to authenticated
    using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
    with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
create policy "Doar administratorii gestionează capitolele"
    on public.limba_capitole for all to authenticated
    using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
    with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
create policy "Doar administratorii gestionează materialele"
    on public.limba_materiale for all to authenticated
    using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
    with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
