// Asamblează panoul de administrare din formulare/componente mici.
const ADMIN_PANEL_HTML = [
    ADMIN_PANEL_PREFIX_HTML,
    ADMIN_AUTHOR_FORM_HTML,
    ADMIN_WORK_FORM_HTML,
    ADMIN_LANGUAGE_CHAPTER_FORM_HTML,
    ADMIN_LANGUAGE_MATERIAL_FORM_HTML,
    ADMIN_LANGUAGE_LIST_HTML,
    ADMIN_AUTHORS_LIST_HTML,
    ADMIN_WORKS_LIST_HTML,
    ADMIN_PDF_LIST_HTML,
    ADMIN_PANEL_SUFFIX_HTML
].join("");
